name: Daily Commit

on:
  schedule:
    - cron: '23 4 * * *'  # Runs daily at 04:23 UTC
  workflow_dispatch:       # Allows manual triggering for testing

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update file by 24f2006003@ds.study.iitm.ac.in
        run: |
          echo "$(date)" >> daily-log.txt
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add daily-log.txt
          git commit -m "Daily commit on $(date)"
          git push
